/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinistryWomenRouteImport } from './routes/ministry.women'
import { Route as MinistryMenRouteImport } from './routes/ministry.men'
import { Route as MediaSermonsRouteImport } from './routes/media.sermons'
import { Route as MediaGalleryRouteImport } from './routes/media.gallery'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistryWomenRoute = MinistryWomenRouteImport.update({
  id: '/ministry/women',
  path: '/ministry/women',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistryMenRoute = MinistryMenRouteImport.update({
  id: '/ministry/men',
  path: '/ministry/men',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSermonsRoute = MediaSermonsRouteImport.update({
  id: '/media/sermons',
  path: '/media/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaGalleryRoute = MediaGalleryRouteImport.update({
  id: '/media/gallery',
  path: '/media/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/media/gallery': typeof MediaGalleryRoute
  '/media/sermons': typeof MediaSermonsRoute
  '/ministry/men': typeof MinistryMenRoute
  '/ministry/women': typeof MinistryWomenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/media/gallery': typeof MediaGalleryRoute
  '/media/sermons': typeof MediaSermonsRoute
  '/ministry/men': typeof MinistryMenRoute
  '/ministry/women': typeof MinistryWomenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/media/gallery': typeof MediaGalleryRoute
  '/media/sermons': typeof MediaSermonsRoute
  '/ministry/men': typeof MinistryMenRoute
  '/ministry/women': typeof MinistryWomenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/events'
    | '/sitemap.xml'
    | '/api/contact'
    | '/media/gallery'
    | '/media/sermons'
    | '/ministry/men'
    | '/ministry/women'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/events'
    | '/sitemap.xml'
    | '/api/contact'
    | '/media/gallery'
    | '/media/sermons'
    | '/ministry/men'
    | '/ministry/women'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/events'
    | '/sitemap.xml'
    | '/api/contact'
    | '/media/gallery'
    | '/media/sermons'
    | '/ministry/men'
    | '/ministry/women'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiContactRoute: typeof ApiContactRoute
  MediaGalleryRoute: typeof MediaGalleryRoute
  MediaSermonsRoute: typeof MediaSermonsRoute
  MinistryMenRoute: typeof MinistryMenRoute
  MinistryWomenRoute: typeof MinistryWomenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministry/women': {
      id: '/ministry/women'
      path: '/ministry/women'
      fullPath: '/ministry/women'
      preLoaderRoute: typeof MinistryWomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministry/men': {
      id: '/ministry/men'
      path: '/ministry/men'
      fullPath: '/ministry/men'
      preLoaderRoute: typeof MinistryMenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/sermons': {
      id: '/media/sermons'
      path: '/media/sermons'
      fullPath: '/media/sermons'
      preLoaderRoute: typeof MediaSermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/gallery': {
      id: '/media/gallery'
      path: '/media/gallery'
      fullPath: '/media/gallery'
      preLoaderRoute: typeof MediaGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiContactRoute: ApiContactRoute,
  MediaGalleryRoute: MediaGalleryRoute,
  MediaSermonsRoute: MediaSermonsRoute,
  MinistryMenRoute: MinistryMenRoute,
  MinistryWomenRoute: MinistryWomenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
